language: rust
sudo: false
dist: trusty
services:
  - docker

rust:
  - 1.1.0  # Oldest supported version
  - stable
  - beta
  - nightly

script:
  - bash ci/run-travis.sh

env:
  - ARCH=x86_64

os:
  - linux
  - osx

# Failures on nightly shouldn't fail the overall build.
matrix:
  fast_finish: true
  include:
    - os: linux
      env: ARCH=i686
      rust: stable
      sudo: true
    - os: osx
      env: ARCH=i686
      rust: stable
      sudo: true
    - os: linux
      env: TARGET=aarch64-unknown-linux-gnu DOCKER_IMAGE=posborne/rust-cross:arm
      rust: 1.7.0
      sudo: true
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf DOCKER_IMAGE=posborne/rust-cross:arm
      rust: 1.7.0
      sudo: true
    - os: linux
      env: TARGET=mips-unknown-linux-gnu DOCKER_IMAGE=posborne/rust-cross:mips
      rust: 1.7.0
      sudo: true
    - os: linux
      env: TARGET=mipsel-unknwon-linux-gnu DOCKER_IMAGE=posborne/rust-cross:mips
      rust: 1.7.0
      sudo: true
    - os: linux
      env: TARGET=arm-linux-androideabi DOCKER_IMAGE=posborne/rust-cross:android
      rust: 1.7.0
      sudo: true
  allow_failures:
    - rust: nightly
    - env: TARGET=aarch64-unknown-linux-gnu DOCKER_IMAGE=posborne/rust-cross:arm
    - env: TARGET=arm-unknown-linux-gnueabihf DOCKER_IMAGE=posborne/rust-cross:arm
    - env: TARGET=mips-unknown-linux-gnu DOCKER_IMAGE=posborne/rust-cross:mips
    - env: TARGET=mipsel-unknwon-linux-gnu DOCKER_IMAGE=posborne/rust-cross:mips
    - env: TARGET=arm-linux-androideabi DOCKER_IMAGE=posborne/rust-cross:android

# Deploy documentation to S3 for specific branches. At some
# point, it would be nice to also support building docs for
# a specific tag
deploy:
  provider: s3
  access_key_id: AKIAIGFX36YKEFRZJAXA
  secret_access_key:
    secure: Q10KEdtBoYxaGXtt23L00J0obv9fpVWtao8YKFEroZMOmvu8Sq2+9aTNGEQRp2OojOxuu+DjZInJlUDFhq6trmV3kpZH2BF7cNRxiZQpQ2FEmlr6ZpYN38GhcIUKdxXqVwXiASJi6j+vz6QdpaOGCs5lQC3VhM5sn49MFXNUrFU=
  bucket: rustdoc
  endpoint: "rustdoc.s3-website-us-east-1.amazonaws.com"
  skip_cleanup: true
  local-dir: target/doc
  upload-dir: nix/${TRAVIS_BRANCH}/${TRAVIS_OS_NAME}
  acl: public_read
  on:
    condition: "\"$TRAVIS_RUST_VERSION/$ARCH\" == \"1.1.0/x86_64\""
    repo: carllerche/nix-rust
    branch:
      - master
