language: rust
sudo: false
dist: trusty
services:
- docker
addons:
  apt:
    packages:
    - gcc-multilib
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
rust:
- 1.1.0
- 1.7.0
- 1.8.0
- stable
- beta
- nightly
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: U553Lx5dnlAS4wszv3urlHpgpjo8IzquGZdLK8zO9DZTsvZaqIxPmEAcJE4gPKjmSdhfpmqcNpCnKOghM45/annRnGwKH4cZ5Uy8wPRJDjuWXQ/nFi8/15RueeYD1jBEyNn5X+n4LRTiSVqgYodEPISkMJ3t8IicNzIlYVhS1Ac=
  matrix:
  - ARCH=x86_64
  - ARCH=i686
os:
- linux
matrix:
  fast_finish: true
  include:
  - os: osx
    env: ARCH=x86_64
    rust: stable
  - os: osx
    env: ARCH=i686
    rust: stable
  - os: osx
    env: ARCH=x86_64
    rust: 1.1.0
  - os: osx
    env: ARCH=i686
    rust: 1.1.0
  - os: linux
    env: TARGET=aarch64-unknown-linux-gnu DOCKER_IMAGE=posborne/rust-cross:arm
    rust: 1.7.0
    sudo: true
  - os: linux
    env: TARGET=arm-unknown-linux-gnueabihf DOCKER_IMAGE=posborne/rust-cross:arm
    rust: 1.7.0
    sudo: true
  - os: linux
    env: TARGET=mips-unknown-linux-gnu DOCKER_IMAGE=posborne/rust-cross:mips
    rust: 1.7.0
    sudo: true
  - os: linux
    env: TARGET=mipsel-unknown-linux-gnu DOCKER_IMAGE=posborne/rust-cross:mips
    rust: 1.7.0
    sudo: true
  - os: linux
    env: TARGET=arm-linux-androideabi DOCKER_IMAGE=posborne/rust-cross:android
    rust: 1.7.0
    sudo: true
  allow_failures:
  - rust: nightly
  - env: TARGET=mips-unknown-linux-gnu DOCKER_IMAGE=posborne/rust-cross:mips
  - env: TARGET=mipsel-unknown-linux-gnu DOCKER_IMAGE=posborne/rust-cross:mips
  - env: TARGET=arm-linux-androideabi DOCKER_IMAGE=posborne/rust-cross:android
before_script:
- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
- bash ci/run-travis.sh
- travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
- travis-cargo coveralls --no-sudo --verify
